Att.create!([
  {name: "Gaiwan", user_id: 1},
  {name: "Western", user_id: 1},
  {name: "Flavored", user_id: 1},
  {name: "1 infusion", user_id: 1},
  {name: "No Sugar", user_id: 1},
  {name: "Indian", user_id: 1}
])
Wishlist.create!([
  {name: "Organic Oriental Beauty", notes: "2oz $15.50", url: "http://www.arborteas.com/organic-oriental-beauty-oolong-tea.html", user_id: 1},
  {name: "Peach Oolong", notes: "2oz $7", url: "http://www.adagio.com/oolong/peach_oolong.html", user_id: 1},
  {name: "Sample Pack", notes: "$20", url: "http://www.teavivre.com/special-black-tea-pack/", user_id: 1}
])
TeaType.create!([
  {name: "Black"},
  {name: "Oolong"},
  {name: "Green"},
  {name: "Chai"},
  {name: "White"},
  {name: "Rooibos"},
  {name: "Mate"},
  {name: "Herbal"},
  {name: "Blend"},
  {name: "Pu-erh"}
])
Note.create!([
  {title: "About Tea", body: "http://www.teadiscussion.com/types/black-tea.php\r\nCamellia sinensis Plant\r\nWhite, Green, Oolong,Black,Assam,Ceylon\r\n\r\nWhite tea\r\nThe purest and least processed of all teas. It has very little caffeine, 1-2% as much caffeine content as one cup of coffee.\r\n\r\nGreen tea\r\nTea leaves are picked, dried, and heat-treated to stop fermentation. The heat treatment for Chinese green tea consists of roasting the tea leaves in a hot roasting pan whereas Japanese green tea is steamed. After the heat treatment, the tea leaves are typically rolled and dried again. Chinese tea produces a yellowish green liquor and toasted taste while Japanese green tea is dark green in color and has a grassy taste.  Usually 5-10% caffeine of coffee.\r\n\r\nOolong tea\r\nAfter the tea leaves are picked, they are intentionally bruised by shaking.  While the leaves are drying, the edges of the bruised leaves turn reddish in color and the surface becomes light yellow due to fermentation and oxidation.  After some fermentation period the tea leaves are pan fired to create a semi-fermented tea.  Chinese oolong tea is fermented only long enough to achieve 12-20% fermentation and results in a lighter oolong, while a longer period results in 60-70% fermentation of Taiwanese oolong teas giving them a stronger oolong flavor. 10-15% of the caffeine of coffee.\r\n\r\nBlack tea\r\nFully fermented. The process involves withering then rolling of the tea leaves followed by a long period of fermentation.  Then the black tea leaves are fired. 20% as much caffeine of coffee.\r\n\r\nRooibos tea\r\nNaturally sweet and sometimes nutty tea from the South African Red Bush and is often referred to as Red Tea or African Red Tea.  The rooibos tea processing method involves harvesting the red bush leaves, followed by grinding and bruising of the leaves. Then the rooibos is left to ferment and dried to yield a reddish brown needle-like tea.  Green rooibos tea does not have a fermentation step and thus has a lighter taste than red rooibos teas. Caffeine free.    \r\n\r\nMate tea\r\nSouth American yerba mate plant.  Usually from Argentina.The leaves and stems of yerba mate are harvested and then blanched, dried, aged, and finally milled or cut.  Natural energy booster. Same caffeine as coffee without the jitters.\r\n\r\nAssam tea\r\nFrom Assam,India known for its body, briskness, malty flavor, and strong, bright color. Often sold as \"breakfast\" teas. English Breakfast tea, Irish Breakfast tea, and Scottish Breakfast. Generally harvested twice, in a “first flush” and a “second flush.” The first flush is picked during late March. The second flush, harvested later, is the more prized “tippy tea,” named thus for the gold tips that appear on the leaves. This second flush, tippy tea, is sweeter and more full-bodied and is generally considered superior to the first flush tea.\r\n\r\nCeylon\r\nSri Lanka", user_id: 1},
  {title: "Tea Wishlist", body: "need cheap tea for work\r\n\r\nwant ginger tea\r\n\r\ntea tins\r\n4.50 tavana 6oz\r\n4 black rishi teas\r\n2.5 davids\r\n   \r\n------------------------------\r\n \r\nPots/Infusers:\r\n\r\n8oz ceramic like\r\n\r\n2013: personal teapot 8oz or so. Moms house $9 \r\n\r\nfavor smaller teapots. Bigger for guests but that isnt often, the bigger the pot the more tea must be used for multiple infusions", user_id: 1},
  {title: "Feb 2016 orders", body: "Rishi 2/25 $31.10\r\n  -yunnan gold\r\n  -peppermint\r\n\r\nArbor 2/25 $28.74\r\n  -indian black sampler\r\n  -mango black\r\n\r\nVerdant 2/24 $19\r\n  -pine needle green", user_id: 1},
  {title: "Teapot Measurements", body: "Sea Dragon Yixing Teapot 18 oz\r\nCeramic Cobalt blue 26oz\r\nTricolor Yixing 18oz\r\nGui fei yixing 8oz\r\nCeramic coi 12oz\r\nGreen ice tea maker 24oz\r\nLarge blue ice tea maker 66oz", user_id: 1}
])
Tea.create!([
  {name: "Lemon Grass Chai", stock: "In", notes: "1tsp 5 min", url: "Http://enjoyingtea.com", user_id: 1, tea_type_id: 4, vendor: nil, favorite: false, archive: false},
  {name: "Earl Grey", stock: "In", notes: "1tsp 212 3min 1inf", url: "", user_id: 1, tea_type_id: 1, vendor: nil, favorite: false, archive: false},
  {name: " Oriental Beauty", stock: "In", notes: "4 min 2tsp 195", url: "", user_id: 1, tea_type_id: 2, vendor: nil, favorite: false, archive: false},
  {name: "Earl of Anxi", stock: "In", notes: "1tsp  2min 195", url: "", user_id: 1, tea_type_id: 2, vendor: nil, favorite: false, archive: false},
  {name: "Loashan Black", stock: "In", notes: "W: 3tsp 3min \r\nG: 2-3s,+3, 15inf", url: "", user_id: 1, tea_type_id: 1, vendor: nil, favorite: false, archive: false},
  {name: "Spring Tieguanyin", stock: "In", notes: "212 3-6s", url: "", user_id: 1, tea_type_id: 2, vendor: nil, favorite: false, archive: false},
  {name: "Himalayan Beauty", stock: "In", notes: "200, G: 40s, 20s, 45s, 1m\r\nW: 3tsp 3min good ", url: "", user_id: 1, tea_type_id: 1, vendor: nil, favorite: false, archive: false},
  {name: "Shanghai Orchid", stock: "In", notes: "1tsp  175 deg 2m", url: nil, user_id: 1, tea_type_id: 5, vendor: nil, favorite: false, archive: false},
  {name: "Bailin Gongfu Black", stock: "Out", notes: "G:20, 30, 50, 1m10, 1m30\r\nW:1tsp 2 min weak\r\n185deg", url: "http://www.teavivre.com/bailin-gongfu/", user_id: 1, tea_type_id: 1, vendor: "Teavivre", favorite: false, archive: false},
  {name: "Mi Lan Xiang Phoenix Mountain Dancong Oolong", stock: "In", notes: "Rinse\r\nG: 2-4s\r\nW: 2tsp 5min still somewhat weak\r\n3/4 full gaiwan 2min extremely bitter", url: nil, user_id: 1, tea_type_id: 2, vendor: nil, favorite: false, archive: false},
  {name: "Nishi Gyokuro Okumidori", stock: "In", notes: "G: 160deg, 30s, 60s, 90s\r\n1tbl sp 30s weak\r\n\r\n2tbl sp too strong", url: "http://www.rishi-tea.com/product/organic-gyokuro-okumidori-nishi-japanese-green-tea/green-tea", user_id: 1, tea_type_id: 3, vendor: "Rishi", favorite: false, archive: false},
  {name: "Organic Nonpareil Ming Qian Dragon Well Long Jing", stock: "Out", notes: "5 steeps : rinse, 20s, 40s, 70s, 120s, 150s\r\n\r\n175 deg", url: nil, user_id: 1, tea_type_id: 3, vendor: nil, favorite: false, archive: false},
  {name: "Golden Fleece", stock: "In", notes: "G: 205deg, 8sec, +3sec", url: "http://verdanttea.com/teas/golden-fleece/", user_id: 1, tea_type_id: 1, vendor: "Verdant", favorite: false, archive: false},
  {name: "Golden Monkey", stock: "In", notes: "2min 30sec", url: nil, user_id: 1, tea_type_id: 1, vendor: nil, favorite: true, archive: false},
  {name: "Rose Dian Hong", stock: "In", notes: "195deg, 2-3 tblsp, 3-5min\r\n\r\n3 tsp 3min \r\nA little weak, try 3:30\r\n\r\nHimalayan beauty mix:\r\n2 rose, 1 Himalayan 3:30 good", url: "http://www.teavivre.com/rose-black-tea/", user_id: 1, tea_type_id: 1, vendor: "Teavivre", favorite: true, archive: false},
  {name: "Zhen Qu", stock: "In", notes: "1tsp 3 min 212", url: nil, user_id: 1, tea_type_id: 1, vendor: nil, favorite: true, archive: false},
  {name: "Wuyi Mountain Big Red Robe", stock: "In", notes: "208\r\nW: 3tsp 3min, this tea has some sweetness to it. Don't use as much sugar\r\nG: 2-4", url: nil, user_id: 1, tea_type_id: 2, vendor: nil, favorite: false, archive: false},
  {name: "Silver Jasmine Green", stock: "In", notes: "195deg \r\nG:20,40,1m,1:30\r\nW: 2tsp 2m,4m", url: nil, user_id: 1, tea_type_id: 3, vendor: nil, favorite: false, archive: false},
  {name: "Mango", stock: "Out", notes: "2tsp 3min 212\r\n2nd 6min", url: nil, user_id: 1, tea_type_id: 1, vendor: nil, favorite: false, archive: false},
  {name: "Imperial Breakfast Blend", stock: "Out", notes: nil, url: nil, user_id: 1, tea_type_id: 1, vendor: nil, favorite: false, archive: true},
  {name: "Wild Purple Buds Puerh 2012", stock: "Out", notes: nil, url: nil, user_id: 1, tea_type_id: 2, vendor: nil, favorite: false, archive: true},
  {name: "Lychee Oolong", stock: "Out", notes: "1tsp 180 4min", url: nil, user_id: 1, tea_type_id: 2, vendor: nil, favorite: false, archive: true},
  {name: "Maharaja Chai/Samurai Chai Mate", stock: "Out", notes: nil, url: nil, user_id: 1, tea_type_id: 4, vendor: nil, favorite: false, archive: true},
  {name: "Nonpareil Yunnan Dian Hong Chinese Red Black Tea", stock: "Out", notes: nil, url: nil, user_id: 1, tea_type_id: 1, vendor: nil, favorite: false, archive: true},
  {name: "Qilan Wuyi Oolong", stock: "Out", notes: "G: 2-4 sec 208", url: nil, user_id: 1, tea_type_id: 2, vendor: nil, favorite: false, archive: true},
  {name: "Rose Violet Calendula", stock: "Out", notes: "1tsp 4min 180", url: nil, user_id: 1, tea_type_id: 2, vendor: nil, favorite: false, archive: true},
  {name: "Wuyi Gongfu Black", stock: "Out", notes: "G: 205deg 6sec, +3 sec each\r\n\r\n4grams was too little, just do the norm", url: "http://verdanttea.com/teas/wuyi-gongfu-black-tea/", user_id: 1, tea_type_id: 1, vendor: "Verdant", favorite: false, archive: true},
  {name: "Nilgiri", stock: "In", notes: "not listed", url: "http://www.arborteas.com/organic-nilgiri-black-tea.html", user_id: 1, tea_type_id: 1, vendor: "Arbor Teas", favorite: false, archive: false},
  {name: "Gui Fei Oolong", stock: "In", notes: "2tsp 180deg 3min/5/7", url: nil, user_id: 1, tea_type_id: 2, vendor: nil, favorite: false, archive: false},
  {name: "Oprah chai", stock: "Out", notes: "1-1.5 tsp, 200 deg, 2-3 min\r\n\r\nIced: 3tsp?", url: nil, user_id: 1, tea_type_id: 4, vendor: nil, favorite: false, archive: false},
  {name: "Peppermint", stock: "In", notes: "212, 1 tbl sp, 4-5min", url: "http://www.rishi-tea.com/product/peppermint-organic-caffeine-free-herbal-blend/caffeine-free-herbal", user_id: 1, tea_type_id: 8, vendor: "Rishi", favorite: false, archive: false},
  {name: "Himalayan Classic", stock: "In", notes: "195, 1tbl (4gr), 3min, 4-5min", url: "http://www.rishi-tea.com/product/himalayan-classic-organic-black-tea/black-tea", user_id: 1, tea_type_id: 1, vendor: "Rishi", favorite: false, archive: false},
  {name: "Assam TGFOP", stock: "In", notes: "not listed", url: "http://www.arborteas.com/organic-assam-tgfop-black-tea.html", user_id: 1, tea_type_id: 1, vendor: "Arbor Teas", favorite: false, archive: false},
  {name: "Jin Jun Mei", stock: "Out", notes: "G: 205deg, 6sec, +3sec", url: "http://verdanttea.com/teas/jin-jun-mei/", user_id: 1, tea_type_id: 1, vendor: "Verdant", favorite: false, archive: false},
  {name: "Ancient Golden Yunnan", stock: "In", notes: "212, 1 table sp, 4min, 5min WAY TOO STRONG\r\n\r\n2tsp, 3 min, ok, maybe try 4min\r\nNo so great. Use for ice tea", url: "http://www.rishi-tea.com/product/ancient-golden-yunnan-organic-fair-trade-black-tea/black-tea", user_id: 1, tea_type_id: 1, vendor: "Rishi", favorite: false, archive: false},
  {name: "Laoshan Pine Needle Green", stock: "In", notes: "W: 175deg, 4grams, 20 sec, +10sec\r\nG: 175deg, 4g, 10sec, +4sec\r\n4grams was weak\r\n\r\nWestern 5grams 20 sec perfect!", url: "http://verdanttea.com/teas/laoshan-pine-needle-green/", user_id: 1, tea_type_id: 3, vendor: "Verdant", favorite: false, archive: false},
  {name: "Ruby Oolong", stock: "Out", notes: "W: 195, 1 tbl, 3min, 4, 5min\r\n\r\nG: 1 min, 20 seconds, 50 seconds, subsequent infusions about 2 minutes\r\n\r\nGROSS!!!!", url: "http://www.rishi-tea.com/product/ruby-oolong-organic-oolong-tea/oolong-tea", user_id: 1, tea_type_id: 2, vendor: "Rishi", favorite: false, archive: true},
  {name: "1994 Aged Bai Hao", stock: "Out", notes: nil, url: nil, user_id: 1, tea_type_id: 2, vendor: "Butiki", favorite: false, archive: true},
  {name: "Da Hong Pao (Big Red Robe) Wuyi Rock Oolong Tea Fujian", stock: "In", notes: "G: 212 7 steeps : rinse, 25s, 30s, 40s, 60s, 80s, 120s", url: "http://www.teavivre.com/da-hong-pao-oolong/", user_id: 1, tea_type_id: 2, vendor: "Teavivre", favorite: false, archive: false},
  {name: "Ginger Peach", stock: "In", notes: "3oz $6 Marty's\r\n1tsp 3min, weak, sweet, gingery, not much tea flavor", url: "memteaimports.com", user_id: 1, tea_type_id: 1, vendor: "Mem Tea Imports", favorite: false, archive: false},
  {name: "Mango (arbor teas)", stock: "In", notes: "2 tsp 3min, tad sweet", url: "http://www.arborteas.com/organic-mango-black-tea.html", user_id: 1, tea_type_id: 1, vendor: "Arbor Teas", favorite: false, archive: false},
  {name: "Traditional Tieguanyin", stock: "Out", notes: "eh. nothing special", url: nil, user_id: 1, tea_type_id: 2, vendor: nil, favorite: false, archive: true},
  {name: "Peach Oolong", stock: "Out", notes: "1 tsp 180 4min", url: nil, user_id: 1, tea_type_id: 2, vendor: nil, favorite: false, archive: false},
  {name: "Darjeeling Makaibari Estate 2nd Flush", stock: "Out", notes: "212 2tsp 3min, ok, try 4min", url: "http://www.arborteas.com/organic-darjeeling-makaibari-estate-2nd-flush-black-tea.html", user_id: 1, tea_type_id: 1, vendor: "Arbor Teas", favorite: false, archive: true},
  {name: "South Indian", stock: "Out", notes: "2tsp, 3min", url: "http://www.arborteas.com/organic-south-indian-black-tea.html", user_id: 1, tea_type_id: 1, vendor: "Arbor Teas", favorite: false, archive: true},
  {name: "Lychee Black", stock: "In", notes: "212 1tsp 3min lil weak, try 2tsp 2min", url: "http://www.arborteas.com/organic-lychee-black-tea.html", user_id: 1, tea_type_id: 1, vendor: "Arbor Teas", favorite: false, archive: false},
  {name: "Strawberry Grapefruit Xue Long", stock: "In", notes: "1.5-2tsp 175 2min\r\n\r\nartificial tasting. use for ice tea only", url: nil, user_id: 1, tea_type_id: 3, vendor: "Teavana", favorite: false, archive: false}
])
Tea::HABTM_Atts.create!([
  {att_id: 1, tea_id: 1},
  {att_id: 2, tea_id: 2},
  {att_id: 3, tea_id: 3},
  {att_id: 2, tea_id: 3},
  {att_id: 3, tea_id: 4},
  {att_id: 3, tea_id: 5},
  {att_id: 2, tea_id: 5},
  {att_id: 1, tea_id: 5},
  {att_id: 2, tea_id: 6},
  {att_id: 2, tea_id: 7},
  {att_id: 2, tea_id: 8},
  {att_id: 2, tea_id: 9},
  {att_id: 3, tea_id: 10},
  {att_id: 2, tea_id: 10},
  {att_id: 3, tea_id: 12},
  {att_id: 2, tea_id: 12},
  {att_id: 2, tea_id: 13},
  {att_id: 3, tea_id: 14},
  {att_id: 2, tea_id: 14},
  {att_id: 2, tea_id: 15},
  {att_id: 1, tea_id: 15},
  {att_id: 1, tea_id: 16},
  {att_id: 1, tea_id: 17},
  {att_id: 1, tea_id: 18},
  {att_id: 1, tea_id: 19},
  {att_id: 1, tea_id: 20},
  {att_id: 1, tea_id: 21},
  {att_id: 1, tea_id: 22},
  {att_id: 2, tea_id: 23},
  {att_id: 1, tea_id: 23},
  {att_id: 2, tea_id: 24},
  {att_id: 1, tea_id: 24},
  {att_id: 1, tea_id: 25},
  {att_id: 2, tea_id: 26},
  {att_id: 3, tea_id: 27},
  {att_id: 2, tea_id: 27},
  {att_id: 4, tea_id: 7},
  {att_id: 4, tea_id: 8},
  {att_id: 4, tea_id: 28},
  {att_id: 2, tea_id: 28},
  {att_id: 5, tea_id: 25},
  {att_id: 5, tea_id: 20},
  {att_id: 5, tea_id: 18},
  {att_id: 5, tea_id: 16},
  {att_id: 5, tea_id: 14},
  {att_id: 5, tea_id: 10},
  {att_id: 5, tea_id: 5},
  {att_id: 2, tea_id: 29},
  {att_id: 1, tea_id: 29},
  {att_id: 2, tea_id: 30},
  {att_id: 5, tea_id: 31},
  {att_id: 1, tea_id: 31},
  {att_id: 2, tea_id: 32},
  {att_id: 1, tea_id: 33},
  {att_id: 5, tea_id: 34},
  {att_id: 2, tea_id: 34},
  {att_id: 1, tea_id: 34},
  {att_id: 1, tea_id: 35},
  {att_id: 2, tea_id: 36},
  {att_id: 1, tea_id: 36},
  {att_id: 3, tea_id: 32},
  {att_id: 2, tea_id: 37},
  {att_id: 5, tea_id: 38},
  {att_id: 2, tea_id: 38},
  {att_id: 2, tea_id: 39},
  {att_id: 2, tea_id: 40},
  {att_id: 1, tea_id: 40},
  {att_id: 3, tea_id: 41},
  {att_id: 2, tea_id: 41},
  {att_id: 3, tea_id: 42},
  {att_id: 2, tea_id: 42},
  {att_id: 2, tea_id: 43},
  {att_id: 2, tea_id: 44},
  {att_id: 2, tea_id: 45},
  {att_id: 2, tea_id: 46},
  {att_id: 6, tea_id: 45},
  {att_id: 6, tea_id: 46},
  {att_id: 6, tea_id: 44},
  {att_id: 6, tea_id: 43},
  {att_id: 3, tea_id: 47},
  {att_id: 2, tea_id: 47},
  {att_id: 2, tea_id: 48},
  {att_id: 3, tea_id: 48}
])
Preference.create!([
  {name: "night_mode_default", value: "false", user_id: 1}
])
